name: main

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '9 */10 * * *'
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name : composer install
        shell: bash
        run : |
          php -v
          composer install  -q --no-ansi --no-interaction --no-progress
      - name : phpunit
        shell: bash
        run : |
          vendor/bin/phpunit
      - name : log
        shell: bash
        run : |
          date -I > last-tested.txt
      - name: push updated lists
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update tested date.
  run-composer-install:
    runs-on: ubuntu-latest
    steps:
      - name:  installation
        shell: bash
        run: |
          php -v
          composer require takuya/php-sysv-ipc-semaphore
          cat <<'EOS' > sample.php
          <?php
          require_once 'vendor/autoload.php';
          use Takuya\SysV\IPCSemaphore;
          $semaphore = new IPCSemaphore('sample');
          $ret[] = $semaphore->acquire();
          $ret[] = $semaphore->acquire(true);
          $ret[] = $semaphore->release();
          $ret[] = $semaphore->destroy();
          var_dump( $ret == [true,false,true,true]);
          EOS
          cat sample.php
          php sample.php